import React, { useState } from 'react';
import { X, Download, FileText, Calendar, MapPin, User, Shield, AlertTriangle } from 'lucide-react';
import jsPDF from 'jspdf';

interface Detection {
  id: string;
  class: string;
  confidence: number;
  bbox: [number, number, number, number];
  description: string;
  forensicSignificance: string;
}

interface AnalysisResult {
  detections: Detection[];
  imageUrl: string;
  timestamp: string;
  metadata: {
    resolution: string;
    fileSize: string;
    format: string;
  };
}

interface ForensicReportProps {
  result: AnalysisResult;
  onClose: () => void;
}

const ForensicReport: React.FC<ForensicReportProps> = ({ result, onClose }) => {
  const caseNumber = `CASE-${Date.now().toString().slice(-8)}`;
  const reportDate = new Date().toLocaleDateString();
  const analysisTime = new Date(result.timestamp).toLocaleString();
  const [isGeneratingPDF, setIsGeneratingPDF] = useState(false);
  const [crimeSceneLocation, setCrimeSceneLocation] = useState('');
  const [investigatorName, setInvestigatorName] = useState('');
  const [showInputs, setShowInputs] = useState(false);

  const downloadPDF = async () => {
    if (!crimeSceneLocation.trim() || !investigatorName.trim()) {
      setShowInputs(true);
      return;
    }

    setIsGeneratingPDF(true);
    
    try {
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      const margin = 20;
      let yPosition = margin;
      
      // Helper function to check if we need a new page
      const checkNewPage = (requiredHeight: number) => {
        if (yPosition + requiredHeight > pageHeight - margin) {
          pdf.addPage();
          yPosition = margin;
          return true;
        }
        return false;
      };

      // Helper function to add text with word wrapping
      const addText = (text: string, fontSize: number = 10, isBold: boolean = false, color: string = 'black') => {
        pdf.setFontSize(fontSize);
        if (isBold) {
          pdf.setFont('helvetica', 'bold');
        } else {
          pdf.setFont('helvetica', 'normal');
        }
        
        // Set text color
        if (color === 'blue') {
          pdf.setTextColor(0, 100, 200);
        } else if (color === 'red') {
          pdf.setTextColor(200, 0, 0);
        } else {
          pdf.setTextColor(0, 0, 0);
        }
        
        const lines = pdf.splitTextToSize(text, pageWidth - 2 * margin);
        const lineHeight = fontSize * 0.35;
        
        checkNewPage(lines.length * lineHeight + 5);
        
        pdf.text(lines, margin, yPosition);
        yPosition += lines.length * lineHeight + 5;
        
        // Reset color to black
        pdf.setTextColor(0, 0, 0);
      };

      // Add header with blue background
      pdf.setFillColor(0, 100, 200);
      pdf.rect(0, 0, pageWidth, 40, 'F');
      
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(20);
      pdf.setFont('helvetica', 'bold');
      pdf.text('FORENSIC ANALYSIS REPORT', pageWidth / 2, 20, { align: 'center' });
      
      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'normal');
      pdf.text('Generated by ForensicAI Analyzer v2.1', pageWidth / 2, 30, { align: 'center' });
      
      yPosition = 50;
      pdf.setTextColor(0, 0, 0);
      
      // Case Information Box
      pdf.setFillColor(240, 248, 255);
      pdf.rect(margin, yPosition, pageWidth - 2 * margin, 50, 'F');
      pdf.setDrawColor(0, 100, 200);
      pdf.rect(margin, yPosition, pageWidth - 2 * margin, 50, 'S');
      
      yPosition += 10;
      addText('CASE INFORMATION', 14, true, 'blue');
      
      const caseInfo = [
        `Case Number: ${caseNumber}`,
        `Report Date: ${reportDate}`,
        `Crime Scene Location: ${crimeSceneLocation}`,
        `Lead Investigator: ${investigatorName}`,
        `Analysis Timestamp: ${analysisTime}`,
        `AI Model: YOLO v11 Forensic Detection System`
      ];
      
      caseInfo.forEach(info => {
        addText(info, 10);
      });
      
      yPosition += 10;
      
      // Technical Details Box
      pdf.setFillColor(248, 250, 252);
      pdf.rect(margin, yPosition, pageWidth - 2 * margin, 30, 'F');
      pdf.setDrawColor(100, 116, 139);
      pdf.rect(margin, yPosition, pageWidth - 2 * margin, 30, 'S');
      
      yPosition += 10;
      addText('TECHNICAL SPECIFICATIONS', 12, true);
      addText(`Image Resolution: ${result.metadata.resolution} | File Size: ${result.metadata.fileSize} | Format: ${result.metadata.format}`, 10);
      
      yPosition += 15;
      
      // Evidence Summary with colored boxes
      addText('EVIDENCE SUMMARY', 14, true, 'blue');
      
      const criticalCount = result.detections.filter(d => d.confidence > 0.9 && ['knife', 'gun', 'weapon'].includes(d.class.toLowerCase())).length;
      const avgConfidence = Math.round(result.detections.reduce((acc, d) => acc + d.confidence, 0) / result.detections.length * 100);
      
      // Summary boxes
      const summaryY = yPosition;
      const boxWidth = (pageWidth - 4 * margin) / 3;
      
      // Total Items box
      pdf.setFillColor(59, 130, 246);
      pdf.rect(margin, summaryY, boxWidth, 20, 'F');
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(16);
      pdf.setFont('helvetica', 'bold');
      pdf.text(result.detections.length.toString(), margin + boxWidth/2, summaryY + 10, { align: 'center' });
      pdf.setFontSize(8);
      pdf.text('TOTAL ITEMS', margin + boxWidth/2, summaryY + 16, { align: 'center' });
      
      // Critical Items box
      pdf.setFillColor(239, 68, 68);
      pdf.rect(margin + boxWidth + 5, summaryY, boxWidth, 20, 'F');
      pdf.text(criticalCount.toString(), margin + boxWidth + 5 + boxWidth/2, summaryY + 10, { align: 'center' });
      pdf.text('CRITICAL ITEMS', margin + boxWidth + 5 + boxWidth/2, summaryY + 16, { align: 'center' });
      
      // Confidence box
      pdf.setFillColor(34, 197, 94);
      pdf.rect(margin + 2 * boxWidth + 10, summaryY, boxWidth, 20, 'F');
      pdf.text(`${avgConfidence}%`, margin + 2 * boxWidth + 10 + boxWidth/2, summaryY + 10, { align: 'center' });
      pdf.text('AVG CONFIDENCE', margin + 2 * boxWidth + 10 + boxWidth/2, summaryY + 16, { align: 'center' });
      
      yPosition += 35;
      pdf.setTextColor(0, 0, 0);
      
      // Critical Evidence Alert
      if (criticalCount > 0) {
        pdf.setFillColor(254, 242, 242);
        pdf.rect(margin, yPosition, pageWidth - 2 * margin, 20, 'F');
        pdf.setDrawColor(239, 68, 68);
        pdf.rect(margin, yPosition, pageWidth - 2 * margin, 20, 'S');
        
        yPosition += 8;
        addText('⚠ CRITICAL EVIDENCE ALERT', 12, true, 'red');
        addText(`${criticalCount} high-priority evidence item(s) detected requiring immediate attention and secure chain of custody procedures.`, 10);
        yPosition += 5;
      }
      
      // Detailed Evidence Catalog
      addText('DETAILED EVIDENCE CATALOG', 14, true, 'blue');
      
      result.detections.forEach((detection, index) => {
        checkNewPage(60);
        
        // Evidence item header
        pdf.setFillColor(249, 250, 251);
        pdf.rect(margin, yPosition, pageWidth - 2 * margin, 8, 'F');
        pdf.setDrawColor(209, 213, 219);
        pdf.rect(margin, yPosition, pageWidth - 2 * margin, 8, 'S');
        
        yPosition += 6;
        addText(`Evidence Item #${index + 1} - ${detection.class.replace('_', ' ').toUpperCase()}`, 12, true);
        
        // Evidence details
        const evidenceDetails = [
          `ID: ${detection.id}`,
          `Confidence Level: ${Math.round(detection.confidence * 100)}%`,
          `Location Coordinates: [${detection.bbox.join(', ')}]`,
          `Description: ${detection.description}`,
          `Forensic Significance: ${detection.forensicSignificance}`,
          `Recommended Action: Immediate collection and chain of custody documentation required`
        ];
        
        evidenceDetails.forEach(detail => {
          addText(`• ${detail}`, 9);
        });
        
        yPosition += 5;
      });
      
      // Recommendations section
      checkNewPage(80);
      addText('INVESTIGATIVE RECOMMENDATIONS', 14, true, 'blue');
      
      const recommendations = [
        'Secure the crime scene and establish proper perimeter control with law enforcement personnel',
        'Document all evidence locations with high-resolution photography before any collection activities',
        'Collect physical evidence following established chain of custody procedures and protocols',
        'Submit all biological samples to certified forensic laboratory for comprehensive DNA analysis',
        'Process latent fingerprint evidence through AFIS (Automated Fingerprint Identification System)',
        'Conduct detailed ballistics analysis for any firearm-related evidence discovered',
        'Interview witnesses and suspects based on evidence findings and location data',
        'Coordinate with forensic specialists for additional analysis as required by case complexity'
      ];
      
      recommendations.forEach((rec, index) => {
        addText(`${index + 1}. ${rec}`, 10);
      });
      
      // Chain of Custody
      checkNewPage(40);
      addText('CHAIN OF CUSTODY DOCUMENTATION', 14, true, 'blue');
      
      const custodyInfo = [
        `Digital Evidence Created: ${analysisTime}`,
        `AI Analysis Completed: ${new Date().toLocaleString()}`,
        `Report Generated: ${new Date().toLocaleString()}`,
        `Processing System: ForensicAI Analyzer v2.1 (YOLO v11)`,
        `Lead Investigator: ${investigatorName}`,
        `Crime Scene Location: ${crimeSceneLocation}`,
        `Case Reference: ${caseNumber}`,
        `Digital Signature: SHA-256 Hash [SIMULATED FOR DEMO]`
      ];
      
      custodyInfo.forEach(info => {
        addText(`• ${info}`, 10);
      });
      
      // Footer with disclaimer
      checkNewPage(30);
      pdf.setFillColor(255, 251, 235);
      pdf.rect(margin, yPosition, pageWidth - 2 * margin, 25, 'F');
      pdf.setDrawColor(245, 158, 11);
      pdf.rect(margin, yPosition, pageWidth - 2 * margin, 25, 'S');
      
      yPosition += 8;
      addText('IMPORTANT LEGAL DISCLAIMER', 12, true, 'red');
      addText('This report was generated using AI-powered forensic analysis technology. All findings must be verified by qualified forensic experts and laboratory analysis. This digital analysis serves as preliminary evidence identification and should not be used as sole evidence in legal proceedings. All evidence must be processed according to local, state, and federal forensic standards.', 9);
      
      // Final footer
      yPosition = pageHeight - 20;
      pdf.setFontSize(8);
      pdf.setFont('helvetica', 'normal');
      pdf.text(`Report ID: ${caseNumber} | Generated: ${new Date().toISOString()} | ForensicAI v2.1`, pageWidth / 2, yPosition, { align: 'center' });
      
      // Save the PDF
      pdf.save(`Forensic_Analysis_Report_${caseNumber}.pdf`);
      
    } catch (error) {
      console.error('Error generating PDF:', error);
      alert('Error generating PDF. Please try again.');
    } finally {
      setIsGeneratingPDF(false);
      setShowInputs(false);
    }
  };

  const criticalEvidence = result.detections.filter(d => 
    d.confidence > 0.9 && ['knife', 'gun', 'weapon'].includes(d.class.toLowerCase())
  );

  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <div className="bg-slate-900 border border-blue-400/20 rounded-2xl max-w-4xl w-full max-h-[90vh] overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-blue-400/20">
          <div className="flex items-center space-x-3">
            <div className="p-2 bg-blue-500/20 rounded-lg">
              <FileText className="w-6 h-6 text-blue-400" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-white">Forensic Analysis Report</h2>
              <p className="text-sm text-slate-400">Case #{caseNumber}</p>
            </div>
          </div>
          <div className="flex items-center space-x-3">
            <button
              onClick={downloadPDF}
              disabled={isGeneratingPDF}
              className="flex items-center space-x-2 bg-green-500 hover:bg-green-600 disabled:bg-green-500/50 disabled:cursor-not-allowed px-4 py-2 rounded-lg font-medium transition-colors"
            >
              {isGeneratingPDF ? (
                <>
                  <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></div>
                  <span>Generating...</span>
                </>
              ) : (
                <>
                  <Download className="w-4 h-4" />
                  <span>Download PDF</span>
                </>
              )}
            </button>
            <button
              onClick={onClose}
              className="p-2 hover:bg-slate-700 rounded-lg transition-colors"
            >
              <X className="w-5 h-5 text-slate-400" />
            </button>
          </div>
        </div>

        {/* Input Modal */}
        {showInputs && (
          <div className="absolute inset-0 bg-black/70 backdrop-blur-sm flex items-center justify-center z-10">
            <div className="bg-slate-800 border border-blue-400/20 rounded-xl p-6 max-w-md w-full mx-4">
              <h3 className="text-lg font-bold text-white mb-4">Report Information Required</h3>
              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-slate-300 mb-2">
                    Crime Scene Location *
                  </label>
                  <input
                    type="text"
                    value={crimeSceneLocation}
                    onChange={(e) => setCrimeSceneLocation(e.target.value)}
                    placeholder="e.g., 123 Main Street, Downtown District"
                    className="w-full px-3 py-2 bg-slate-700 border border-slate-600 rounded-lg text-white placeholder-slate-400 focus:border-blue-400 focus:outline-none"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-slate-300 mb-2">
                    Lead Investigator Name *
                  </label>
                  <input
                    type="text"
                    value={investigatorName}
                    onChange={(e) => setInvestigatorName(e.target.value)}
                    placeholder="e.g., Detective John Smith"
                    className="w-full px-3 py-2 bg-slate-700 border border-slate-600 rounded-lg text-white placeholder-slate-400 focus:border-blue-400 focus:outline-none"
                  />
                </div>
              </div>
              <div className="flex space-x-3 mt-6">
                <button
                  onClick={downloadPDF}
                  disabled={!crimeSceneLocation.trim() || !investigatorName.trim()}
                  className="flex-1 bg-green-500 hover:bg-green-600 disabled:bg-green-500/50 disabled:cursor-not-allowed px-4 py-2 rounded-lg font-medium transition-colors text-white"
                >
                  Generate Report
                </button>
                <button
                  onClick={() => setShowInputs(false)}
                  className="px-4 py-2 bg-slate-600 hover:bg-slate-700 rounded-lg font-medium transition-colors text-white"
                >
                  Cancel
                </button>
              </div>
            </div>
          </div>
        )}

        {/* Content */}
        <div className="p-6 overflow-y-auto max-h-[calc(90vh-5rem)]">
          <div className="space-y-8">
            {/* Report Header */}
            <div className="bg-black/30 rounded-xl p-6 border border-blue-400/10">
              <div className="grid md:grid-cols-2 gap-6">
                <div className="space-y-3">
                  <div className="flex items-center space-x-2">
                    <Calendar className="w-4 h-4 text-blue-400" />
                    <span className="text-sm text-slate-300">Report Date:</span>
                    <span className="text-sm font-medium text-white">{reportDate}</span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <User className="w-4 h-4 text-blue-400" />
                    <span className="text-sm text-slate-300">Analyst:</span>
                    <span className="text-sm font-medium text-white">ForensicAI System v2.1</span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <Shield className="w-4 h-4 text-blue-400" />
                    <span className="text-sm text-slate-300">AI Model:</span>
                    <span className="text-sm font-medium text-white">YOLO v11 Forensic</span>
                  </div>
                </div>
                <div className="space-y-3">
                  <div className="flex items-center space-x-2">
                    <MapPin className="w-4 h-4 text-blue-400" />
                    <span className="text-sm text-slate-300">Analysis Time:</span>
                    <span className="text-sm font-medium text-white">{analysisTime}</span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <FileText className="w-4 h-4 text-blue-400" />
                    <span className="text-sm text-slate-300">Resolution:</span>
                    <span className="text-sm font-medium text-white">{result.metadata.resolution}</span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <FileText className="w-4 h-4 text-blue-400" />
                    <span className="text-sm text-slate-300">File Size:</span>
                    <span className="text-sm font-medium text-white">{result.metadata.fileSize}</span>
                  </div>
                </div>
              </div>
            </div>

            {/* Executive Summary */}
            <div>
              <h3 className="text-lg font-semibold text-white mb-4">Executive Summary</h3>
              <div className="bg-black/30 rounded-xl p-6 border border-blue-400/10">
                <div className="grid md:grid-cols-3 gap-4 mb-4">
                  <div className="text-center p-4 bg-blue-500/10 rounded-lg border border-blue-400/20">
                    <div className="text-2xl font-bold text-blue-400">{result.detections.length}</div>
                    <div className="text-sm text-slate-300">Evidence Items</div>
                  </div>
                  <div className="text-center p-4 bg-red-500/10 rounded-lg border border-red-400/20">
                    <div className="text-2xl font-bold text-red-400">{criticalEvidence.length}</div>
                    <div className="text-sm text-slate-300">Critical Items</div>
                  </div>
                  <div className="text-center p-4 bg-green-500/10 rounded-lg border border-green-400/20">
                    <div className="text-2xl font-bold text-green-400">
                      {Math.round(result.detections.reduce((acc, d) => acc + d.confidence, 0) / result.detections.length * 100)}%
                    </div>
                    <div className="text-sm text-slate-300">Avg Confidence</div>
                  </div>
                </div>

                {criticalEvidence.length > 0 && (
                  <div className="bg-red-500/10 border border-red-400/30 rounded-lg p-4 flex items-start space-x-3">
                    <AlertTriangle className="w-5 h-5 text-red-400 mt-0.5" />
                    <div>
                      <h4 className="font-medium text-red-400 mb-1">Critical Evidence Alert</h4>
                      <p className="text-sm text-slate-300">
                        {criticalEvidence.length} high-priority evidence item(s) detected requiring immediate attention and secure chain of custody procedures.
                      </p>
                    </div>
                  </div>
                )}
              </div>
            </div>

            {/* Evidence Catalog */}
            <div>
              <h3 className="text-lg font-semibold text-white mb-4">Detailed Evidence Catalog</h3>
              <div className="space-y-4">
                {result.detections.map((detection, index) => (
                  <div key={detection.id} className="bg-black/30 rounded-xl p-6 border border-blue-400/10">
                    <div className="flex items-start justify-between mb-4">
                      <div>
                        <h4 className="font-semibold text-white text-lg">
                          Evidence Item #{index + 1}
                        </h4>
                        <p className="text-blue-400 font-medium capitalize">
                          {detection.class.replace('_', ' ')}
                        </p>
                      </div>
                      <div className="text-right">
                        <div className="text-lg font-bold text-green-400">
                          {Math.round(detection.confidence * 100)}%
                        </div>
                        <div className="text-sm text-slate-400">Confidence</div>
                      </div>
                    </div>

                    <div className="grid md:grid-cols-2 gap-4">
                      <div>
                        <h5 className="font-medium text-slate-300 mb-2">Description</h5>
                        <p className="text-sm text-slate-400">{detection.description}</p>
                      </div>
                      <div>
                        <h5 className="font-medium text-slate-300 mb-2">Location Coordinates</h5>
                        <p className="text-sm text-slate-400 font-mono">
                          [{detection.bbox.join(', ')}]
                        </p>
                      </div>
                    </div>

                    <div className="mt-4">
                      <h5 className="font-medium text-slate-300 mb-2">Forensic Significance</h5>
                      <div className="bg-blue-500/10 border border-blue-400/20 rounded-lg p-3">
                        <p className="text-sm text-blue-300">{detection.forensicSignificance}</p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Recommendations */}
            <div>
              <h3 className="text-lg font-semibold text-white mb-4">Recommendations</h3>
              <div className="bg-black/30 rounded-xl p-6 border border-blue-400/10">
                <div className="space-y-3 text-sm text-slate-300">
                  <div className="flex items-start space-x-2">
                    <span className="text-blue-400 font-medium">1.</span>
                    <span>Secure the crime scene and establish proper perimeter control</span>
                  </div>
                  <div className="flex items-start space-x-2">
                    <span className="text-blue-400 font-medium">2.</span>
                    <span>Document all evidence with high-resolution photography before collection</span>
                  </div>
                  <div className="flex items-start space-x-2">
                    <span className="text-blue-400 font-medium">3.</span>
                    <span>Collect physical evidence following proper chain of custody procedures</span>
                  </div>
                  <div className="flex items-start space-x-2">
                    <span className="text-blue-400 font-medium">4.</span>
                    <span>Submit biological samples for laboratory DNA analysis</span>
                  </div>
                  <div className="flex items-start space-x-2">
                    <span className="text-blue-400 font-medium">5.</span>
                    <span>Process fingerprint evidence through AFIS database comparison</span>
                  </div>
                  <div className="flex items-start space-x-2">
                    <span className="text-blue-400 font-medium">6.</span>
                    <span>Conduct ballistics analysis for firearm-related evidence</span>
                  </div>
                </div>
              </div>
            </div>

            {/* Disclaimer */}
            <div className="bg-yellow-500/10 border border-yellow-400/30 rounded-xl p-4">
              <div className="flex items-start space-x-2">
                <AlertTriangle className="w-5 h-5 text-yellow-400 mt-0.5" />
                <div>
                  <h4 className="font-medium text-yellow-400 mb-1">Important Disclaimer</h4>
                  <p className="text-sm text-slate-300">
                    This report was generated using AI-powered forensic analysis. All findings should be verified by qualified forensic experts and laboratory analysis. This digital analysis serves as preliminary evidence identification and should not be used as sole evidence in legal proceedings.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ForensicReport;